apiVersion: v1
kind: Service
metadata:
  annotations:
    description: App service
  labels:
    name: "%{SELECTOR}"
  name: "%{SELECTOR}"
spec:
  ports:
  - name: "%{SELECTOR}"
    port: "%{PORT}"
    protocol: TCP
    targetPort: "%{PORT}"
  selector:
    name: "%{SELECTOR}"
  sessionAffinity: None