apiVersion: v1
kind: Route
metadata:
  labels:
    app: "%{ROUTE_NAME}"
  name: "%{ROUTE_NAME}"
spec:
  host: "%{ROUTE_ADDRESS}"
  port:
    targetPort: "%{SERVICE_NAME}"
  to:
    kind: Service
    name: "%{SERVICE_NAME}"
    weight: 100
  wildcardPolicy: None