apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    description: Database deployment
  name: "%{APP_NAME}"
  labels:
    app: "%{APP_NAME}"
spec:
  revisionHistoryLimit: 5
  replicas: 1
  selector:
    name: "%{APP_NAME}"
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      labels:
        name: "%{APP_NAME}"
      name: "%{APP_NAME}"
    spec:
      containers:
      - env:
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: "%{DATABASE_SECRET_NAME}"
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: "%{DATABASE_SECRET_NAME}"
        - name: POSTGRESQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database-name
              name: "%{DATABASE_SECRET_NAME}"
        - name: POSTGRESQL_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-admin-password
              name: "%{DATABASE_SECRET_NAME}"
        - name: POSTGRESQL_MAX_CONNECTIONS
          value: '100'
        - name: POSTGRESQL_SHARED_BUFFERS
          value: 12MB
        image: "centos/postgresql-10-centos7"
        imagePullPolicy: Always
        name: "%{APP_NAME}"
        ports:
        - containerPort: 5432
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 200m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: "%{CLAIM_NAME}"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: "%{CLAIM_NAME}"
        persistentVolumeClaim:
         claimName: "%{CLAIM_NAME}"
  test: false
  triggers:
  - type: ConfigChange