kind: Secret
apiVersion: v1
stringData:
  database-connection-string: "Server=%{HOST};Port=5432;Database=%{DATABASE_NAME};User Id=%{USER_NAME};Password=%{PASSWORD};"
  database-name: "%{DATABASE_NAME}"
  database-user: "%{USER_NAME}"
  database-password: "%{PASSWORD}"
  database-admin-password: "%{PASSWORD}"
metadata:
  name: "%{SECRET-NAME}"
type: Opaque