apiVersion: v1
data:
  ${KAFKA_SSL_CA_FILENAME}: "${CA_KAFKA}"
  ${KAFKA_SSL_CERT_FILENAME}: "${CERTIFICATE_KAFKA}"
  ${KAFKA_SSL_KEY_FILENAME}: "${KEY_KAFKA}"
kind: ConfigMap
metadata:
  name: ${KAFKA_SSL_CONFIG_MAP_NAME}